name: Terraform Deployment
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Debug OIDC audience
        run: |
          curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          | jq -r '.value' | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .

      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://54.92.212.47:8200
          role: gh-actions-role
          method: jwt
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
